<!-- nav.inc -->
	
	<nav class=HorNav>
	<div class=navfloat>
		<a class=navfloat class="active" href=index.php>Home</a>
		<a class=navfloat href=courses.php>Courses</a>
		<a class=navfloat href=Subjects.php>Subjects</a>
		<a class=navfloat href=Instructors.php>Instructors</a>
		<a class=navfloat href=Add.php>Add</a>
		</div>
	</nav>
	<nav class=VerNav>
		<a class="active" href=index.php>Home</a><br>
		<a href=courses.php>Courses</a><br>
		<a href=Subjects.php>Subjects</a><br>
		<a href=Instructors.php>Instructors</a><br>
		<a href=Add.php>Add</a><br>
	</nav>
<!-- end of nav.inc -->
